version: '3.1'

services:
  #elasticsearch 镜像
  elasticsearch:
    build:
      context: .
      dockerfile: elasticsearch.dockerfile
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
       - "/data/es2:/usr/share/elasticsearch/data"

  #kibana 可视化查询，暴露 5601
  kibana:
    image: kibana:5.6
    links:
      - elasticsearch
    ports:
      - 5601:5601
    depends_on:
      - "elasticsearch"

  #skywalking
  skywalking:
    build:
      context: .
      dockerfile: skywalking.dockerfile
    ports:
      - "10800:10800"
      - "11800:11800"
      - "12800:12800"
      - "8082:8080"
    links:
      - elasticsearch
    depends_on:
      - "elasticsearch"
